### ISSUE TITLE
Invalid Hook Call Error

### ISSUE THREAD

**Issue by cdwetal** [k-128/react-tradingview-embed#13]
Hello,

I am attempting to use this component, but it is not working in a fresh empty React app. I created the app using the command:

`npx create-react-app my-app --template typescript`

Then installed this component using the command:

`npm install --save react-tradingview-embed`

Then I replaced the contents of App.tsx with the code:

```
import { AdvancedChart } from "react-tradingview-embed";

const App = () => <AdvancedChart widgetProps={{"theme": "dark"}} />;

export default App;
```

I am now receiving this error when running the project:

```
react.development.js:1476 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at Object.useEffect (react.development.js:1519:1)
    at AdvancedChart (AdvancedChart.js:9:1)
    at renderWithHooks (react-dom.development.js:16141:1)
    at mountIndeterminateComponent (react-dom.development.js:20838:1)
    at beginWork (react-dom.development.js:22342:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4157:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:1)
    at invokeGuardedCallback (react-dom.development.js:4270:1)
    at beginWork$1 (react-dom.development.js:27243:1)
react-dom.development.js:18525 The above error occurred in the <AdvancedChart> component:

    at AdvancedChart (http://localhost:3000/static/js/bundle.js:37485:5)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18525
bootstrap:27 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at Object.useEffect (react.development.js:1519:1)
    at AdvancedChart (AdvancedChart.js:9:1)
    at renderWithHooks (react-dom.development.js:16141:1)
    at mountIndeterminateComponent (react-dom.development.js:20838:1)
    at beginWork (react-dom.development.js:22342:1)
    at beginWork$1 (react-dom.development.js:27219:1)
    at performUnitOfWork (react-dom.development.js:26392:1)
    at workLoopSync (react-dom.development.js:26303:1)
    at renderRootSync (react-dom.development.js:26271:1)
```

Please let me know how I can fix this issue.

**Comment by k-128** [comment]
Updating to the latest version should fix your issue.

Seems it was a compatibility issue with the new React 18, I've bumped the deps and the issue was gone on my side.

**Comment by k-128** [comment]
Updating to the latest version (curr: 3.0.1) should fix your issue.

Seems it was a compatibility issue with the new React 18.

**Comment by k-128** [comment]
Updating to the latest version (curr: 3.0.1) should fix your issue.

The problem came from the new React 18 release, it seems bumping the deps was enough, let me know if your issue persist, if not I will close it.

**Comment by k-128** [comment]
Updating to the latest version (curr: 3.0.6) should fix your issue.
